site_name: NLP for Drone Flight Log Analysis
site_url: https://dronenlp.github.io/documentation/
site_description: Unlocking Insights from Drone Flight Logs with NLP.
site_author: Swardiantara Silalahi

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  logo: assets/logo_ncc.png

nav:
  - Home:
    - home/index.md
    - About the Project: home/about.md
    - Contact: home/contact.md
  - Data Preparation:
    - methodology/index.md
    - Data Collection: methodology/data-collection.md
    - Data Cleansing: methodology/cleansing.md
    - Data Splitting: methodology/data-splitting.md
  - Tasks & Datasets:
    - tasks/index.md
    - Event Recognition: tasks/event-recognition.md
    - Problem Identification: tasks/problem-identification.md
    - Log Abstraction: tasks/log-abstraction.md
    - Term Extraction: tasks/term-extraction.md
    - Semantic Role Labeling: tasks/semantic-role-labeling.md
  - Publications:
    - publications/index.md
    - Problem Identification: publications/problem-identification.md
    - Term Extraction: publications/term-extraction.md
    - Sequence Mining: publications/sequence-mining.md
  - Blog: blog/index.md
  - Dataset Download: download.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


plugins:
  - search
  - blog:
      blog_toc: true
      post_dir: blog/posts
      post_url_prefix: blog/
      blog_dir: blog/
      archive_dir: blog/archive
      categories_dir: blog/categories
      authors_dir: blog/authors
      post_template: blog/post.html
extra_javascript:
  - assets/js/analytics.js

copyright: Copyright &copy; 2025 Net-centric Computing Lab